{
  "swagger": "2.0",
  "info": {
    "title": "MetaShare Api",
    "description": "MetaShare 相關 Api"
  },
  "host": "mata-share-backend.herokuapp.com",
  "basePath": "/",
  "tags": [],
  "schemes": [
    "http",
    "https"
  ],
  "securityDefinitions":{
    "Bearer":{
      "type": "apiKey",
      "in": "headers",
      "name": "Authorization",
      "description": "JWT Token"
    }
  },
  "consumes": [],
  "produces": [],
  "paths": {
    "/api/user/check": {
      "get": {
        "tags": ["User"],
        "description": "檢查使用者是否登入",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "$ref":"#/definitions/postSuccessResponse"
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          }
        }
      }
    },
    "/api/user/register": {
      "post": {
        "tags": ["User"],
        "description": "註冊",
        "parameters": [
          {
            "name": "obj",
            "in": "body",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "example": "Chia Yu"
                },
                "email": {
                  "type": "string",
                  "example": "test@gmail.com"
                },
                "password": {
                  "type": "string",
                  "example": "a1234567"
                }
              },"required": [
                "name",
                "email",
                "password"
              ]
            },
            "type": "string"
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "$ref":"#/definitions/isAuth"
            }
          },
          "400 (欄位為空)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "欄位未正確填寫！"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (密碼小於8碼)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "密碼字數低於 8 碼"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (密碼複雜度低)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "密碼需英數混合"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (Email 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "Email 格式不正確"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (重複註冊)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "此 E-mail 已被註冊"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/user/login": {
      "post": {
        "tags": ["User"],
        "description": "登入",
        "parameters": [
          {
            "name": "obj",
            "in": "body",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "example": "test@gmail.com"
                },
                "password": {
                  "type": "string",
                  "example": "a1234567"
                }
              },"required": [
                "email",
                "password"
              ]
            },
            "type": "string"
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "$ref":"#/definitions/isAuth"
            }
          },
          "400 (欄位為空)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "欄位未正確填寫！"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (Email 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "Email 格式不正確"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (帳號密碼錯誤)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "輸入的帳號或密碼不正確"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/user/checkEmail": {
      "post": {
        "tags": ["Forget Password"],
        "description": "取得驗證碼",
        "parameters": [
          {
            "name": "obj",
            "in": "body",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "example": "test@gmail.com"
                }
              },"required": [
                "email"
              ]
            },
            "type": "string"
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "message": {
                  "type": "string",
                  "example": "寄送驗證碼至Email"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (欄位為空)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "欄位未正確填寫！"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (Email 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "Email 格式不正確"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (Email 尚未註冊)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'此 E-mail 尚未註冊"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/user/verification": {
      "post": {
        "tags": ["Forget Password"],
        "description": "驗證驗證碼",
        "parameters": [
          {
            "name": "obj",
            "in": "body",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "example": "test@gmail.com"
                },
                "verification": {
                  "type": "string",
                  "example": "1234"
                }
              },"required": [
                "email",
                "verification"
              ]
            },
            "type": "string"
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "data": {
                  "type": "object",
                  "example": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzEwMDU0N2VmNjliNzI2ODllNjdmNiIsImlzUmVzZXRQYXNzd29yZCI6ZmFsc2UsImlhdCI6MTY1MjY4NjUxOSwiZXhwIjoxNjUzMjkxMzE5fQ.9Z9HZoI90XfFJ9j9G620Q9WETqDFksDWCNyt_lDT3t1"
                  }
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (Email欄位為空)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "Email 欄位未正確填寫！"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (Email 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "Email 格式不正確"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (Email 尚未註冊)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'此 E-mail 尚未註冊"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (驗證碼欄位為空)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'請輸入收到的驗證碼！"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (驗證碼錯誤)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'驗證碼輸入錯誤，請重新輸入"
                }  
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/user/resetPassword": {
      "patch": {
        "tags": ["Forget Password"],
        "description": "重設密碼",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "JWT Token (重設密碼用 Token)",
            "required":true,
            "type": "string"
            },
          {
            "name": "obj",
            "in": "body",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "password": {
                  "type": "string",
                  "example": "a1234567"
                },
                "confirmPassword": {
                  "type": "string",
                  "example": "a1234567"
                }
              },"required": [
                "password",
                "confirmPassword"
              ]
            },
            "type": "string"
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "message": {
                  "type": "string",
                  "example": "密碼更新成功"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (未帶重設密碼的 token)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "請輸入E-mail 取得驗證碼"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (重設密碼的 token 失效)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "認證失敗，請重新輸入E-mail 取得驗證碼"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (欄位為空)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'欄位未正確填寫！"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (密碼低於八碼)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'密碼字數低於 8 碼"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (密碼複雜度低)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'密碼需英數混合"
                }  
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (密碼輸入不一致)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'密碼輸入不一致！"
                }  
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/user/profile/{id}": {
      "get": {
        "tags": ["Profile"],
        "security":[{
          "Bearer":[]
        }],
        "description": "取得使用者資訊",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "$ref":"#/definitions/profileSuccessResponse"
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (ID 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "使用者 ID 格式錯誤，請重新確認"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (無此使用者)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "查無此用戶"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/user/profile": {
      "patch": {
        "tags": ["Profile"],
        "security":[{
          "Bearer":[]
        }],
        "description": "修改使用者資訊",
        "parameters": [
          {
            "name": "obj",
            "in": "body",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "example": "Chia Yu"
                },
                "avator": {
                  "type": "string",
                  "example": "https://imgur.com/LwPqBcI.png"
                },
                "coverImage": {
                  "type": "string",
                  "example": "https://imgur.com/h1ZySXl.png"
                },
                "coverImageBlur": {
                  "type": "boolean",
                  "example":true
                },
                "description": {
                  "type": "string",
                  "example":"貓貓好可愛喔"
                },
                "tags": {
                  "type": "array",
                  "example":["旅遊"]
                }
              }
            },
            "type": "string"
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "$ref":"#/definitions/profileSuccessResponse"
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (body 為空)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "請輸入要更新的資訊"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/user/updatePassword": {
      "patch": {
        "tags": ["Profile"],
        "description": "更新密碼",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [
          {
            "name": "obj",
            "in": "body",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "password": {
                  "type": "string",
                  "example": "a1234567"
                },
                "confirmPassword": {
                  "type": "string",
                  "example": "a1234567"
                }
              },"required": [
                "password",
                "confirmPassword"
              ]
            },
            "type": "string"
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "$ref":"#/definitions/isAuth"
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (欄位為空)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'欄位未正確填寫！"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (密碼低於八碼)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'密碼字數低於 8 碼"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (密碼複雜度低)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'密碼需英數混合"
                }  
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (密碼輸入不一致)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "'密碼輸入不一致！"
                }  
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/posts/": {
      "get": {
        "tags": ["Post"],
        "description": "取得全部貼文",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "$ref":"#/definitions/postSuccessResponse"
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          }
        }
      }
    },
    "/api/posts/user/{id}": {
      "get": {
        "tags": ["Post"],
        "description": "取得該使用者貼文",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "$ref":"#/definitions/postSuccessResponse"
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (ID 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "使用者 ID 格式錯誤，請重新確認"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (無此使用者)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "查無此用戶"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/post/{id}": {
      "get": {
        "tags": ["Post"],
        "security":[{
          "Bearer":[]
        }],
        "description": "取得單筆貼文",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "$ref":"#/definitions/postSuccessResponse"
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (ID 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/idFormatErrorResponse"
            }
          },
          "400 (查無此 ID)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundIdErrorResponse"
            }
          }
        }
      },
      "delete": {
        "tags": ["Post"],
        "description": "刪除單筆貼文",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "data": {
                  "type": "array",
                  "example": [{
                    "_id": "62763cb70b6e444e6fd4fbbb",
                    "author": {
                      "_id": "627100547ef69b72689e67f6",
                      "name": "Chia Yu",
                      "avator": "https://imgur.com/LwPqBcI.png"
                    },
                    "content": "123",
                    "imageUrls": [],
                    "likes": [],
                    "createdAt": "2022-05-07T09:32:39.272Z",
                    "comments": []
                  }]
                },
                "message": {
                  "type": "string",
                  "example": "刪除成功"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (ID 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/idFormatErrorResponse"
            }
          },
          "400 (查無此 ID)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundIdErrorResponse"
            }
          }
        }
      },
      "patch": {
        "tags": ["Post"],
        "description": "更新單筆貼文",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },{
            "name": "obj",
            "in": "body",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "content": {
                  "type": "string",
                  "example": "更新內容"
                },
                "imageUrls": {
                  "type": "array",
                  "example": [
                    "https://i.imgur.com/L7EzN1j.png"
                  ]
                }
              }
            },
            "type": "string"
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "data": {
                  "type": "array",
                  "example": [{
                    "_id": "62763cb70b6e444e6fd4fbbb",
                    "author": {
                      "_id": "627100547ef69b72689e67f6",
                      "name": "Chia Yu",
                      "avator": "https://imgur.com/LwPqBcI.png"
                    },
                    "content": "更新內容",
                    "imageUrls": [],
                    "likes": [],
                    "createdAt": "2022-05-07T09:32:39.272Z",
                    "comments": []
                  }]
                },
                "message": {
                  "type": "string",
                  "example": "更新成功"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (沒有更新內容)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "請輸入要更新的貼文內容或圖片"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (ID 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/idFormatErrorResponse"
            }
          },
          "400 (查無此 ID)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundIdErrorResponse"
            }
          },
          "400 (使用者無權限)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "此使用者沒有更新這則貼文的權限"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/post/{id}/likes": {
      "get": {
        "tags": ["Post"],
        "description": "取得單則貼文喜歡的人",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "data": {
                  "type": "array",
                  "example": [ {
                    "_id": "627100547ef69b72689e67f6",
                    "name": "Chia Yu",
                    "avator": "https://imgur.com/LwPqBcI.png"
                }]
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (ID 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/idFormatErrorResponse"
            }
          },
          "400 (查無此 ID)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundIdErrorResponse"
            }
          }
        }
      },
      "patch": {
        "tags": ["Post"],
        "description": "喜歡/收回喜歡",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "data": {
                  "type": "array",
                  "example": [{
                    "_id": "62763cb70b6e444e6fd4fbbb",
                    "author": {
                      "_id": "627100547ef69b72689e67f6",
                      "name": "Chia Yu",
                      "avator": "https://imgur.com/LwPqBcI.png"
                    },
                    "content": "更新內容",
                    "imageUrls": [],
                    "likes": [
                      "627100547ef69b72689e67f6"
                    ],
                    "createdAt": "2022-05-07T09:32:39.272Z",
                    "comments": []
                  }]
                },
                "message": {
                  "type": "string",
                  "example": "更新成功"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (ID 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/idFormatErrorResponse"
            }
          },
          "400 (查無此 ID)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundIdErrorResponse"
            }
          }
        }
      }
    },
    "/api/post/{id}/comments": {
      "get": {
        "tags": ["Post"],
        "description": "取得單則貼文的留言",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "data": {
                  "type": "array",
                  "example": [{
                    "commenter": {
                      "_id": "627100a67ef69b72689e67f7",
                      "name": "Amy Lin",
                      "avator": "https://imgur.com/m9p1N0H.png"
                    },
                    "content": "哈哈",
                    "createdAt": "2022-05-04T10:20:06.167Z"
                  },
                  {
                    "commenter": {
                      "_id": "627100547ef69b72689e67f6",
                      "name": "Chia Yu",
                      "avator": "https://imgur.com/LwPqBcI.png"
                    },
                    "content": "笑屁喔",
                    "createdAt": "2022-05-05T10:20:06.167Z"
                  }]
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (ID 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/idFormatErrorResponse"
            }
          },
          "400 (查無此 ID)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundIdErrorResponse"
            }
          }
        }
      },
      "patch": {
        "tags": ["Post"],
        "description": "新增留言",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },{
            "name": "obj",
            "in": "body",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "content": {
                  "type": "string",
                  "example": "留言內容"
                }
              },
              "required": [
                "content"
              ]
            },
            "type": "string"
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "data": {
                  "type": "array",
                  "example": [{
                    "_id": "62763a35b90092b5356055ab",
                    "author": "627100547ef69b72689e67f6",
                    "content": "更新內容2",
                    "imageUrls": [
                        "https://i.imgur.com/L7EzN1j.png"
                    ],
                    "likes": [],
                    "createdAt": "2022-05-07T09:21:57.477Z",
                    "comments": [
                        {
                            "commenter": "627100547ef69b72689e67f6",
                            "content": "留言",
                            "createdAt": "2022-05-08T09:40:42.081Z",
                            "_id": "6277901ac3db681a968b7c65"
                        }
                    ]
                }]
                },
                "message": {
                  "type": "string",
                  "example": "留言成功"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (沒有留言內容)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "請輸入留言內容"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (ID 格式錯誤)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/idFormatErrorResponse"
            }
          },
          "400 (查無此 ID)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundIdErrorResponse"
            }
          }
        }
      }
    },
    "/api/post/": {
      "post": {
        "tags": ["Post"],
        "description": "新增貼文",
        "security":[{
          "Bearer":[]
        }],
        "parameters": [
          {
            "name": "obj",
            "in": "body",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "content": {
                  "type": "string",
                  "example": "貼文內容"
                },
                "imageUrls": {
                  "type": "array",
                  "example": [
                    "https://i.imgur.com/L7EzN1j.png"
                  ]
                }
              }
            },
            "type": "string"
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "data": {
                  "type": "array",
                  "example": [{
                    "_id": "62763cb70b6e444e6fd4fbbb",
                    "author": {
                      "_id": "627100547ef69b72689e67f6",
                      "name": "Chia Yu",
                      "avator": "https://imgur.com/LwPqBcI.png"
                    },
                    "content": "更新內容",
                    "imageUrls": [],
                    "likes": [],
                    "createdAt": "2022-05-07T09:32:39.272Z",
                    "comments": []
                  }]
                },
                "message": {
                  "type": "string",
                  "example": "更新成功"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (沒有貼文內容)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "請輸入貼文內容或上傳一張圖片"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/api/uploadImage/": {
      "post": {
        "tags": ["uploadImage"],
        "description": "上傳圖片",
        "security":[{
          "Bearer":[]
        }],
        "consumes":["multipart/form-data"],
        "parameters": [
          {
            "name": "image",
            "in": "formData",
            "type": "file",
            "description": "資料格式",
            "required":true,
            "schema": {
              "type": "object",
              "properties": {
                "image": {
                  "type": "string",
                  "format": "binary"
              }
              },
              "required": [
                "image"
              ]
            }
            }
        ],
        "responses": {
          "200": {
            "description": "成功回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "success"
                },
                "data": {
                  "type": "object",
                  "example":  {
                    "imageUrl": "https://i.imgur.com/nPlGaBz.png"
                }
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (未帶 Token)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/notFoundToken"
            }
          },
          "400 (Token 失效)": {
            "description": "失敗回應",
            "schema": {
              "$ref":"#/definitions/invalidToken"
            }
          },
          "400 (檔案類型錯誤)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "圖片格式錯誤，僅限 JPG、PNG、JPEG 圖片"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (檔案過大)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "圖片檔案過大，僅限 1mb 以下檔案"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (未選擇圖片上傳)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "請選擇一張圖片上傳"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400 (上傳失敗)": {
            "description": "失敗回應",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": false
                },
                "message": {
                  "type": "string",
                  "example": "上傳失敗，請重新上傳"
                }
              
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "notFoundToken":{
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "example": false
        },
        "message": {
          "type": "string",
          "example": "尚未登入！"
        }
      
      },
      "xml": {
        "name": "main"
      }
    },
    "invalidToken":{
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "example": false
        },
        "message": {
          "type": "string",
          "example": "認證失敗，請重新登入"
        }
      
      },
      "xml": {
        "name": "main"
      }
    },
    "isAuth":{
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "example": "success"
        },
        "data": {
          "type": "array",
          "example": [{
            "_id": "62763cb70b6e444e6fd4fbbb",
            "name": "Chia Yu",
            "avator": "https://imgur.com/LwPqBcI.png",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzEwMDU0N2VmNjliNzI2ODllNjdmNiIsImlzUmVzZXRQYXNzd29yZCI6ZmFsc2UsImlhdCI6MTY1MjY4NjUxOSwiZXhwIjoxNjUzMjkxMzE5fQ.9Z9HZoI90XfFJ9j9G620Q9WETqDFksDWCNyt_lDT3t1"
          }]
        }
      },
      "xml": {
        "name": "main"
      }
    },
    "postSuccessResponse":{
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "example": "success"
        },
        "data": {
          "type": "array",
          "example": [{
            "_id": "62763cb70b6e444e6fd4fbbb",
            "author": {
              "_id": "627100547ef69b72689e67f6",
              "name": "Chia Yu",
              "avator": "https://imgur.com/LwPqBcI.png"
            },
            "content": "123",
            "imageUrls": [],
            "likes": [],
            "createdAt": "2022-05-07T09:32:39.272Z",
            "comments": []
          }]
        }
      
      },
      "xml": {
        "name": "main"
      }
    },
    "profileSuccessResponse":{
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "example": "success"
        },
        "data": {
          "type": "object",
          "example": {
            "_id": "62763cb70b6e444e6fd4fbbb",
            "tags": [
              "貓派",
              "傳說對決",
              "旅遊"
          ],
          "description": "貓貓好可愛\n",
          "user": {
              "_id": "627100547ef69b72689e67f6",
              "name": "Chia Yu",
              "avator": "https://imgur.com/LwPqBcI.png"
          },
          "coverImage": "https://imgur.com/h1ZySXl.png",
          "coverImageBlur": true
          }
        }
      
      },
      "xml": {
        "name": "main"
      }
    },
    "idFormatErrorResponse":{
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "example": false
        },
        "message": {
          "type": "string",
          "example": "貼文 ID 格式錯誤，請重新確認"
        }
      
      },
      "xml": {
        "name": "main"
      }
    },
    "userIdErrorResponse":{
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "example": false
        },
        "message": {
          "type": "string",
          "example": "認證失敗，請重新登入"
        }
      
      },
      "xml": {
        "name": "main"
      }
    },
    "notFoundIdErrorResponse":{
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "example": false
        },
        "message": {
          "type": "string",
          "example": "查無此篇貼文，貼文已不存在"
        }
      
      },
      "xml": {
        "name": "main"
      }
    },
    "errorResponse":{
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "example": false
        },
        "message": {
          "type": "string",
          "example": "系統錯誤，請洽系統管理員"
        }
      
      },
      "xml": {
        "name": "main"
      }
    }
  }
}